SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
HEIGHT_OFFSET = SCREEN_HEIGHT / 10
FPS_LIMIT = 60

DEFAULT_FONT = "Courier"
DEFAULT_FONT_SIZE = 30

DRAW_LINE_WIDTH = 2
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)

STATE_GAME = "GAME"
STATE_GAMEOVER = "GAMEOVER"

SCORE_SCREEN_POS = (10, 10)

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8   # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_SPEED = 40
ASTEROID_MAX_SPEED = 100
ASTEROID_BASE_POINTS = 100

PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_START_POS = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)

SHOT_RADIUS = 5